version: '3.8'
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    container_name: db
    environment:
      - POSTGRES_DB=localdb
      - POSTGRES_PASSWORD=localdb
      - POSTGRES_USER=localdb
    restart: always
    ports:
      - '5432:5432'