name: Postman Acceptance Tests

on:
  push:
    branches:
      - '71-implement-postman-integration-with-ci-pipeline'
  #workflow_run:
    #workflows: ["Maven Docker Push"]
    #branches: [main]
    #types: 
      #- completed

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Prepare API and DB for test run
        uses: isbang/compose-action@v1.4.0
        with:
          compose-file: './docker-compose.api-pull.yml'
          up-flags: '-d'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make directory for test results
        run: mkdir -p testResults

      - name: Run Postman collection
        #run: |
        #  newman run ./src/test/postman/postman-tests.json -x -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme
        run: |
          newman run ./src/test/postman/postman-tests.json
      
      - name: Output the run details
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: testResults        
    