name: Postman Acceptance Tests

on:
  push:
    branches:
      - '71-implement-postman-integration-with-ci-pipeline'
  #workflow_run:
    #workflows: ["Maven Docker Push"]
    #branches: [main]
    #types: 
      #- completed

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Run docker compose on API and DB
        run: |
          docker compose -f .\docker-compose.api-pull.yml up

      - name: Wait for API and DB to start
        run: sleep 45s

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make directory for test results
        run: mkdir -p testResults

      - name: Run Postman collection
        #run: |
        #  newman run ./src/test/postman/postman-tests.json -x -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme
        run: |
          newman run ./src/test/postman/postman-tests.json
      
      - name: Output the run details
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: testResults        
    
